---
namespace: techolsy
name: integration
version: 0.1.1
readme: README.md
authors:
  - "Alexander Olsson <alexander@techolsy.eu>"
description: "Personal collection"
repository: https://github.com/techolsy/integration
